#!/usr/bin/env python3
"""
gen_skills_svg.py -- builds the animated skill-bar SVGs used in the profile README.

Everything is self-contained (no external fonts, no CSS <style> blocks) because
GitHub sanitizes <style>/<script> out of markdown. Animation uses SMIL <animate>,
which DOES run on GitHub's raw-content renderer.

Usage:  python3 bin/gen_skills_svg.py
Output: github-profile/fozayelibnayaz/assets/skills-*.svg
        (assets/now.svg is generated by auto_update.py -- see the note in main())
"""
from __future__ import annotations

import html
import os
import re

OUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                       "github-profile", "fozayelibnayaz", "assets")

PALETTE = {
    "cyan":    ("#22d3ee", "#0891b2"),
    "violet":  ("#a78bfa", "#7c3aed"),
    "amber":   ("#fbbf24", "#d97706"),
    "rose":    ("#fb7185", "#e11d48"),
    "emerald": ("#34d399", "#059669"),
    "sky":     ("#60a5fa", "#2563eb"),
}

CARD_W = 1000
PAD_X = 26
BAR_X = 246
BAR_W = 640
ROW_H = 44
HEADER_H = 74
PAD_B = 30


def build(title: str, subtitle: str, accent: str, rows: list[tuple[str, int]]) -> str:
    """rows: [(label, percent), ...]"""
    top, bottom = PALETTE[accent]
    gid = f"g-{accent}"
    height = HEADER_H + ROW_H * len(rows) + PAD_B

    parts: list[str] = []
    parts.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CARD_W}" height="{height}" '
        f'viewBox="0 0 {CARD_W} {height}" role="img" aria-label="{html.escape(title)}">'
    )
    parts.append(
        "<defs>"
        f'<linearGradient id="{gid}" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0%" stop-color="{top}"/><stop offset="100%" stop-color="{bottom}"/>'
        "</linearGradient>"
        '<linearGradient id="card" x1="0" y1="0" x2="0" y2="1">'
        '<stop offset="0%" stop-color="#0e1526"/><stop offset="100%" stop-color="#0a0f1c"/>'
        "</linearGradient>"
        "</defs>"
    )

    # card body
    parts.append(
        f'<rect x="1" y="1" width="{CARD_W-2}" height="{height-2}" rx="16" fill="url(#card)" '
        f'stroke="#1f2a44" stroke-width="1"/>'
    )
    # accent glow bar on the left edge
    parts.append(
        f'<rect x="1" y="1" width="5" height="{height-2}" rx="2" fill="url({gid})" opacity="0.9"/>'
    )

    # header
    parts.append(
        f'<text x="{PAD_X + 6}" y="40" font-family="ui-monospace, Menlo, Consolas, monospace" '
        f'font-size="21" font-weight="700" fill="#e6edf3" letter-spacing="0.5">'
        f"{html.escape(title)}</text>"
    )
    parts.append(
        f'<text x="{PAD_X + 6}" y="60" font-family="ui-sans-serif, Helvetica, Arial, sans-serif" '
        f'font-size="12.5" fill="#7d8ba5">{html.escape(subtitle)}</text>'
    )
    parts.append(
        f'<line x1="{PAD_X + 6}" y1="70" x2="{CARD_W - PAD_X}" y2="70" stroke="#1f2a44" stroke-width="1"/>'
    )

    for i, (label, pct) in enumerate(rows):
        pct = max(0, min(100, pct))
        y = HEADER_H + i * ROW_H + 8
        bar_y = y + 12
        parts.append(
            f'<text x="{PAD_X + 6}" y="{y + 16}" font-family="ui-sans-serif, Helvetica, Arial, sans-serif" '
            f'font-size="14" fill="#c9d4e6">{html.escape(label)}</text>'
        )
        # track
        parts.append(
            f'<rect x="{BAR_X}" y="{bar_y}" width="{BAR_W}" height="10" rx="5" fill="#16203a"/>'
        )
        # fill with SMIL grow animation
        w = int(BAR_W * pct / 100)
        delay = 0.08 * i
        parts.append(
            f'<rect x="{BAR_X}" y="{bar_y}" width="{w}" height="10" rx="5" fill="url(#{gid})">'
            f'<animate attributeName="width" from="0" to="{w}" dur="0.9s" '
            f'begin="{delay:.2f}s" fill="freeze" calcMode="spline" '
            f'keyTimes="0;1" keySplines="0.16 1 0.3 1"/>'
            f"</rect>"
        )
        # shine tip
        parts.append(
            f'<circle cx="{BAR_X + w}" cy="{bar_y + 5}" r="4" fill="#ffffff" opacity="0.85">'
            f'<animate attributeName="cx" from="{BAR_X}" to="{BAR_X + w}" dur="0.9s" '
            f'begin="{delay:.2f}s" fill="freeze" calcMode="spline" '
            f'keyTimes="0;1" keySplines="0.16 1 0.3 1"/>'
            f"</circle>"
        )
        # percent
        parts.append(
            f'<text x="{BAR_X + BAR_W + 16}" y="{y + 16}" font-family="ui-monospace, Menlo, Consolas, monospace" '
            f'font-size="13" font-weight="700" fill="{top}">{pct}%</text>'
        )

    parts.append("</svg>")
    return "".join(parts)


def build_now_card(items: list[tuple[str, str]], accent: str = "emerald") -> str:
    """A 'what I am working on right now' card."""
    top, bottom = PALETTE[accent]
    height = 74 + 40 * len(items) + 24
    gid = f"g-{accent}"
    p = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{CARD_W}" height="{height}" '
        f'viewBox="0 0 {CARD_W} {height}" role="img" aria-label="Currently">',
        "<defs>"
        f'<linearGradient id="{gid}" x1="0" y1="0" x2="1" y2="0">'
        f'<stop offset="0%" stop-color="{top}"/><stop offset="100%" stop-color="{bottom}"/>'
        "</linearGradient>"
        '<linearGradient id="card2" x1="0" y1="0" x2="0" y2="1">'
        '<stop offset="0%" stop-color="#0e1526"/><stop offset="100%" stop-color="#0a0f1c"/>'
        "</linearGradient></defs>",
        f'<rect x="1" y="1" width="{CARD_W-2}" height="{height-2}" rx="16" fill="url(#card2)" stroke="#1f2a44"/>',
        f'<rect x="1" y="1" width="5" height="{height-2}" rx="2" fill="url(#{gid})"/>',
        f'<circle cx="{PAD_X + 12}" cy="36" r="6" fill="{top}">'
        f'<animate attributeName="opacity" values="1;0.25;1" dur="1.8s" repeatCount="indefinite"/></circle>',
        f'<text x="{PAD_X + 28}" y="42" font-family="ui-monospace, Menlo, Consolas, monospace" '
        f'font-size="19" font-weight="700" fill="#e6edf3">CURRENTLY</text>',
        f'<text x="{PAD_X + 190}" y="42" font-family="ui-sans-serif, Helvetica, Arial, sans-serif" '
        f'font-size="13" fill="#7d8ba5">updated August 2026</text>',
        f'<line x1="{PAD_X + 6}" y1="58" x2="{CARD_W - PAD_X}" y2="58" stroke="#1f2a44"/>',
    ]
    for i, (k, v) in enumerate(items):
        y = 74 + i * 40 + 26
        p.append(
            f'<text x="{PAD_X + 6}" y="{y}" font-family="ui-monospace, Menlo, Consolas, monospace" '
            f'font-size="13" font-weight="700" fill="{top}">{html.escape(k)}</text>'
        )
        p.append(
            f'<text x="{PAD_X + 210}" y="{y}" font-family="ui-sans-serif, Helvetica, Arial, sans-serif" '
            f'font-size="14" fill="#c9d4e6">{html.escape(v)}</text>'
        )
    p.append("</svg>")
    return "".join(p)


SKILL_SETS = {
    "skills-frontend.svg": dict(
        title="FRONTEND  //  interfaces people actually enjoy using",
        subtitle="React ecosystem, typed JavaScript, design-to-production handoff",
        accent="cyan",
        rows=[
            ("JavaScript (ES6+)", 92),
            ("TypeScript", 85),
            ("React.js", 90),
            ("Next.js", 85),
            ("HTML5 / CSS3", 95),
            ("Figma (UI/UX)", 80),
        ],
    ),
    "skills-backend.svg": dict(
        title="BACKEND & CLOUD  //  the part that has to not break",
        subtitle="APIs, containers, managed cloud, relational + document stores",
        accent="violet",
        rows=[
            ("Node.js / Express", 85),
            ("Python", 82),
            ("MySQL / MariaDB", 84),
            ("Supabase / Firebase", 78),
            ("Docker / Kubernetes", 72),
            ("Google Cloud Platform", 70),
        ],
    ),
    "skills-data.svg": dict(
        title="DATA & ANALYTICS  //  decisions backed by evidence",
        subtitle="Measurement, BI dashboards, forecasting, big-data tooling",
        accent="amber",
        rows=[
            ("GA4 + Google Tag Manager", 93),
            ("Looker Studio", 88),
            ("SQL", 88),
            ("Pandas / NumPy", 80),
            ("Prophet / ARIMA / LSTM", 74),
            ("Hadoop / Hive / Spark", 68),
        ],
    ),
    "skills-wp.svg": dict(
        title="WORDPRESS & GROWTH  //  shipping client revenue",
        subtitle="Themes, ACF architecture, technical SEO, Core Web Vitals",
        accent="rose",
        rows=[
            ("WordPress", 93),
            ("ACF + Custom Post Types", 90),
            ("WooCommerce", 85),
            ("Elementor", 84),
            ("Technical SEO / JSON-LD", 86),
            ("Core Web Vitals / Speed", 84),
        ],
    ),
    "skills-qa.svg": dict(
        title="QA & TOOLING  //  shipped means tested",
        subtitle="Automation, API testing, machine-learning pipelines, 3D streaming",
        accent="sky",
        rows=[
            ("Playwright (E2E QA)", 82),
            ("Postman / API testing", 88),
            ("GitHub Actions / CI", 80),
            ("Machine Learning", 78),
            ("Unreal Engine (Pixel Streaming)", 60),
            ("Java / C++ / C / PHP", 66),
        ],
    ),
}

NOW_ITEMS = [
    ("BUILDING", "AI YouTube Command Center - Next.js + OAuth + 30 AI tools"),
    ("SHIPPING", "Eagle 3D Analytics Hub - Streamlit + MongoDB, 4x daily pipeline"),
    ("LEARNING", "LLM function-calling, advanced Playwright, Kubernetes"),
    ("READING", "Designing Data-Intensive Applications (Kleppmann)"),
    ("STATUS", "Open to Full-Stack / Data Analyst / WordPress roles"),
]


def main() -> None:
    os.makedirs(OUT_DIR, exist_ok=True)
    written = []
    for name, spec in SKILL_SETS.items():
        svg = build(spec["title"], spec["subtitle"], spec["accent"], spec["rows"])
        path = os.path.join(OUT_DIR, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(svg)
        written.append((name, len(svg)))

    # NOTE: assets/now.svg is owned by auto_update.py, not by this script.
    # build_now_card() lives here only so auto_update.py can import it.

    for name, size in written:
        print(f"  wrote {name:26} {size:>7} bytes")
    print(f"\n{len(written)} SVG assets generated in {OUT_DIR}")


if __name__ == "__main__":
    main()
